#!/usr/bin/env bash
# build-template.sh — fan canonical helper scripts out to their consumers, then
# regenerate the clone-able template/ from canonical plugin sources.
#
# Canonical sources: scripts/*.sh + scripts/*.py (helpers), plugins/vault-kit/**
# (skills + vault skeleton). The fanned-out script copies inside the skills and
# the skeleton's .bin/, and everything under template/, are GENERATED — never
# edit them by hand; edit the canonical file and re-run this script.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SKILLS="$ROOT/plugins/vault-kit/skills"

# 1. Fan out canonical helper scripts.
#    Both skeletons carry the full .bin/ so a scaffolded vault of either layout is
#    self-sufficient for any agent, Claude Code or not.
SKELETONS=("$SKILLS/new-vault/skeleton" "$SKILLS/new-vault/skeleton-multi")
mkdir -p "$SKILLS/ingest-source/scripts" "$SKILLS/lint-vault/scripts"

cp "$ROOT/scripts/extract_pptx.py" "$SKILLS/ingest-source/scripts/extract_pptx.py"
cp "$ROOT/scripts/extract_docx.py" "$SKILLS/ingest-source/scripts/extract_docx.py"
cp "$ROOT/scripts/check-okf.sh"    "$SKILLS/ingest-source/scripts/check-okf.sh"
cp "$ROOT/scripts/find-vault.sh"   "$SKILLS/ingest-source/scripts/find-vault.sh"
cp "$ROOT/scripts/check-okf.sh"    "$SKILLS/lint-vault/scripts/check-okf.sh"
cp "$ROOT/scripts/lint_scan.py"    "$SKILLS/lint-vault/scripts/lint_scan.py"
cp "$ROOT/scripts/find-vault.sh"   "$SKILLS/lint-vault/scripts/find-vault.sh"
chmod +x "$SKILLS"/ingest-source/scripts/*.sh "$SKILLS"/lint-vault/scripts/*.sh

for skel in "${SKELETONS[@]}"; do
  mkdir -p "$skel/.bin"
  cp "$ROOT/scripts/extract_pptx.py" "$ROOT/scripts/extract_docx.py" \
     "$ROOT/scripts/check-okf.sh"    "$ROOT/scripts/lint_scan.py" \
     "$ROOT/scripts/find-vault.sh"   "$skel/.bin/"
  chmod +x "$skel/.bin"/*
done

# 2. Regenerate template/.
rm -rf "$ROOT/template"
mkdir -p "$ROOT/template/.claude/skills"

cp -R "$SKILLS/new-vault/skeleton" "$ROOT/template/vault"
cp -R "$SKILLS/ingest-source"      "$ROOT/template/.claude/skills/ingest-source"
cp -R "$SKILLS/lint-vault"         "$ROOT/template/.claude/skills/lint-vault"

cat > "$ROOT/template/README.md" <<'EOF'
# Knowledge Vault (OKF / LLM-wiki starter)

A starter knowledge vault: an Obsidian-compatible, portable **Open Knowledge Format (OKF)
v0.1** bundle maintained in the **LLM-wiki** style — the agent does the bookkeeping, the
human judges meaning. This directory is a generated export of
[vault-kit](https://github.com/mattraby/vault-kit) for people who want the template without
installing the Claude Code plugin.

## Use it

1. Copy this directory to your project (e.g. `degit mattraby/vault-kit/template my-project`).
2. **Rename `vault/` to `<your-project>-vault/`.** Obsidian takes a vault's display name from
   the directory basename, so several vaults all named "vault" are indistinguishable in the
   switcher. Update the directory-map root line in `AGENTS.md` to match.
3. Open it in [Obsidian](https://obsidian.md).
4. Read `AGENTS.md` — the schema and workflows. Codex and other AGENTS.md-aware tools
   read it natively; Claude Code loads it through the one-line `CLAUDE.md` bridge.
5. Rename the placeholder wiki categories; delete the three worked examples once the pattern
   is clear.
6. Record durable project facts in `MEMORY.md` — it travels with the repo.

## The four layers

`sources/` raw and immutable · `wiki/` synthesized concepts you own · `outputs/` long-form
documents written from the wiki for readers outside the vault · `AGENTS.md` the schema. Wiki
versus output is a question of shape and audience, not subject: a wiki page is one atomic
concept for us, an output is one whole document for someone else.

Helper scripts (vault detection, extraction, conformance check, lint scan) live in `.bin/` for
any agent; the `ingest-source` and `lint-vault` skills in `.claude/skills/` wrap them for
Claude Code.

## Options

This template is the **single-topic** layout: one research subject, layers organized directly by
category. For several unrelated subjects, the vault-kit `new-vault` skill also scaffolds a
**multi-topic** layout (`wiki/<topic>/<category>/`, `sources/<topic>/`, `outputs/<topic>/`),
where each topic owns its own category set. The layout is declared by the `Topics:` line in
`AGENTS.md` and the tooling follows it.

Prefer Obsidian wikilinks over the default markdown links? Change the `Link style:` line in
`AGENTS.md` to `wikilinks` and set `"useMarkdownLinks": false` in `.obsidian/app.json` — the
conformance checker and lint scanner follow the declaration.

> Generated by `scripts/build-template.sh` in vault-kit — do not edit here; edit the plugin source.
EOF

echo "Fanned out helper scripts and built template/ from canonical plugin sources."
