#!/usr/bin/env bash
# build-template.sh — fan canonical helper scripts out to their consumers, then
# regenerate the clone-able template/ from canonical plugin sources.
#
# Canonical sources: scripts/*.sh + scripts/*.py (helpers), plugins/vault-kit/**
# (skills + vault skeleton). The fanned-out script copies inside the skills and
# the skeleton's .bin/, and everything under template/, are GENERATED — never
# edit them by hand; edit the canonical file and re-run this script.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SKILLS="$ROOT/plugins/vault-kit/skills"

# 1. Fan out canonical helper scripts.
BIN="$SKILLS/new-vault/skeleton/.bin"
mkdir -p "$BIN" "$SKILLS/ingest-source/scripts" "$SKILLS/lint-vault/scripts"

cp "$ROOT/scripts/extract_pptx.py" "$SKILLS/ingest-source/scripts/extract_pptx.py"
cp "$ROOT/scripts/extract_docx.py" "$SKILLS/ingest-source/scripts/extract_docx.py"
cp "$ROOT/scripts/check-okf.sh"    "$SKILLS/ingest-source/scripts/check-okf.sh"
cp "$ROOT/scripts/check-okf.sh"    "$SKILLS/lint-vault/scripts/check-okf.sh"
cp "$ROOT/scripts/lint_scan.py"    "$SKILLS/lint-vault/scripts/lint_scan.py"
cp "$ROOT/scripts/extract_pptx.py" "$ROOT/scripts/extract_docx.py" \
   "$ROOT/scripts/check-okf.sh"    "$ROOT/scripts/lint_scan.py"    "$BIN/"
chmod +x "$BIN"/* "$SKILLS/ingest-source/scripts/check-okf.sh" "$SKILLS/lint-vault/scripts/check-okf.sh"

# 2. Regenerate template/.
rm -rf "$ROOT/template"
mkdir -p "$ROOT/template/.claude/skills"

cp -R "$SKILLS/new-vault/skeleton" "$ROOT/template/vault"
cp -R "$SKILLS/ingest-source"      "$ROOT/template/.claude/skills/ingest-source"
cp -R "$SKILLS/lint-vault"         "$ROOT/template/.claude/skills/lint-vault"

cat > "$ROOT/template/README.md" <<'EOF'
# Knowledge Vault (OKF / LLM-wiki starter)

A starter knowledge vault: an Obsidian-compatible, portable **Open Knowledge Format (OKF)
v0.1** bundle maintained in the **LLM-wiki** style — the agent does the bookkeeping, the
human judges meaning. This directory is a generated export of
[vault-kit](https://github.com/mattraby/vault-kit) for people who want the template without
installing the Claude Code plugin.

## Use it

1. Copy this directory to your project (e.g. `degit mattraby/vault-kit/template my-project`).
2. Open `vault/` in [Obsidian](https://obsidian.md).
3. Read `vault/AGENTS.md` — the schema and workflows. Codex and other AGENTS.md-aware tools
   read it natively; Claude Code loads it through the one-line `vault/CLAUDE.md` bridge.
4. Rename the placeholder wiki categories; delete the two worked examples once the pattern
   is clear.
5. Record durable project facts in `vault/MEMORY.md` — it travels with the repo.

Helper scripts (extraction, conformance check, lint scan) live in `vault/.bin/` for any
agent; the `ingest-source` and `lint-vault` skills in `.claude/skills/` wrap them for
Claude Code.

Prefer Obsidian wikilinks over the default markdown links? Change the `Link style:` line in
`vault/AGENTS.md` to `wikilinks` and set `"useMarkdownLinks": false` in
`vault/.obsidian/app.json` — the conformance checker and lint scanner follow the declaration.

> Generated by `scripts/build-template.sh` in vault-kit — do not edit here; edit the plugin source.
EOF

echo "Fanned out helper scripts and built template/ from canonical plugin sources."
